// ============================================================
// Generated by Vox C99 Compiler
// ============================================================

#include "vox_runtime.h"

void main();
vox_int fibonacci(vox_int n);

void main() {
    vox_println_str(vox_str_new("Ola, Mundo! Bem-vindo a linguagem Kael!"));
    vox_str* nome = vox_str_new("Kael");
    vox_float versao = ((vox_float)0.1);
    vox_bool ativo = true;
    vox_println_str(vox_str_concat(vox_str_new("Linguagem: "), nome));
    vox_println_str(vox_str_concat(vox_str_new("Versao: "), vox_int_to_str(float(versao))));
    vox_int x = ((vox_int)10LL);
    vox_int y = ((vox_int)20LL);
    vox_int soma = (x + y);
    vox_println_str(vox_str_concat(vox_str_new("Soma: "), vox_int_to_str(int(soma))));
    if ((soma > ((vox_int)25LL))) {
    vox_println_str(vox_str_new("Soma e maior que 25!"));
}
else {
    vox_println_str(vox_str_new("Soma e menor ou igual a 25."));
}
    vox_array* nums = ({ vox_array* _arr_0 = vox_array_new(5); vox_array_push(_arr_0, (void*)(intptr_t)((vox_int)1LL)); vox_array_push(_arr_0, (void*)(intptr_t)((vox_int)2LL)); vox_array_push(_arr_0, (void*)(intptr_t)((vox_int)3LL)); vox_array_push(_arr_0, (void*)(intptr_t)((vox_int)4LL)); vox_array_push(_arr_0, (void*)(intptr_t)((vox_int)5LL)); _arr_0; });
    vox_println_str(vox_str_new("Contando:"));
    vox_array* _arr_2 = nums;
for (size_t _i_1 = 0; _i_1 < vox_array_len(_arr_2); _i_1++) {
    void* n = vox_array_get(_arr_2, _i_1);
    vox_print_str(vox_str_concat(vox_int_to_str(int(n)), vox_str_new(" ")));
}
    vox_println_str(vox_str_new(""));
    vox_int dobros = nums->map(0);
    vox_println_str(vox_str_concat(vox_str_new("Dobros: "), vox_int_to_str(dobros)));
    vox_int pares = nums->filter(0);
    vox_println_str(vox_str_concat(vox_str_new("Pares: "), vox_int_to_str(pares)));
    vox_println_str(vox_str_concat(vox_str_new("Fibonacci(10) = "), vox_int_to_str(fibonacci(((vox_int)10LL)))));
}

vox_int fibonacci(vox_int n) {
    if ((n <= ((vox_int)1LL))) {
    return n;
}
    return (fibonacci((n - ((vox_int)1LL))) + fibonacci((n - ((vox_int)2LL))));
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    main();
    return 0;
}