// ============================================================
// Generated by Vox v1.0 C99 Compiler
// ============================================================

#include "vox_runtime.h"

vox_int divisao_segura(vox_int a, vox_int b);
vox_option carregar_config(vox_str* chave);
vox_option iniciar_servidor();
vox_option iniciar_servidor_invalido();
vox_int tarefa_paralela(vox_int id, vox_int multiplicador);

vox_int divisao_segura(vox_int a, vox_int b) {
    if ((b == ((vox_int)0LL))) {
    vox_throw((void*)(intptr_t)vox_str_new("Erro: Divisao por zero detectada!"));
}
    return (a / b);
}

vox_option carregar_config(vox_str* chave) {
    if (vox_str_eq(chave, vox_str_new("porta"))) {
    return vox_some((void*)(intptr_t)vox_str_new("8080"));
}
    return vox_none();
}

vox_option iniciar_servidor() {
    vox_str* porta = ({ vox_option _prop_1 = carregar_config(vox_str_new("porta")); if (!_prop_1.is_some) return vox_none(); _prop_1.value; });
    return vox_some((void*)(intptr_t)vox_str_concat(vox_str_new("Servidor rodando na porta "), porta));
}

vox_option iniciar_servidor_invalido() {
    vox_str* host = ({ vox_option _prop_2 = carregar_config(vox_str_new("host")); if (!_prop_2.is_some) return vox_none(); _prop_2.value; });
    return vox_some((void*)(intptr_t)vox_str_concat(vox_str_new("Servidor rodando em "), host));
}

vox_int tarefa_paralela(vox_int id, vox_int multiplicador) {
    vox_println_str(vox_str_concat(vox_str_concat(vox_str_new("  [Thread "), vox_int_to_str(id)), vox_str_new("] Executando em paralelo...")));
    return (id * multiplicador);
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    vox_println_str(vox_str_new("================================================="));
    vox_println_str(vox_str_new("  🪐 VOX v1.1 — DEMONSTRAÇÃO DOS NOVOS RECURSOS"));
    vox_println_str(vox_str_new("================================================="));
    vox_println_str(vox_str_new(""));
    vox_println_str(vox_str_new("--- 1. Tratamento Estruturado de Exceções ---"));
    {
    vox_exception_frame _vox_frame_0;
    vox_push_try_frame(&_vox_frame_0);
    if (setjmp(_vox_frame_0.jmp) == 0) {
        vox_println_str(vox_str_concat(vox_str_new("Calculando 10 / 2 = "), vox_int_to_str(divisao_segura(((vox_int)10LL), ((vox_int)2LL)))));
        vox_println_str(vox_str_new("Tentando dividir 10 / 0..."));
        vox_int falha = divisao_segura(((vox_int)10LL), ((vox_int)0LL));
        vox_println_str(vox_str_concat(vox_str_new("Nao deve alcancar aqui: "), vox_int_to_str(falha)));
        vox_pop_try_frame();
    } else {
        vox_pop_try_frame();
        vox_str* e = (vox_str*)_vox_frame_0.thrown_val;
        vox_println_str(vox_str_concat(vox_str_new(">> Excecao capturada com sucesso: "), e));
    }
    {
        vox_println_str(vox_str_new(">> Bloco finally executado com sucesso!"));
    }
}
    vox_println_str(vox_str_new(""));
    vox_println_str(vox_str_new("--- 2. Operador de Propagacao de Erro (?) ---"));
    vox_println_str(vox_str_concat(vox_str_new("Configuracao valida:   "), vox_option_to_str(iniciar_servidor())));
    vox_println_str(vox_str_concat(vox_str_new("Configuracao ausente:  "), vox_option_to_str(iniciar_servidor_invalido())));
    vox_println_str(vox_str_new(""));
    vox_println_str(vox_str_new("--- 3. Sistema de Arquivos (File I/O) ---"));
    vox_str* arquivo_exemplo = vox_str_new("temp_vox_v1_1.txt");
    vox_file_write(arquivo_exemplo, vox_str_new("Vox v1.1 - Sistema de Arquivos Nativo\nLinha 2 do arquivo!\n"));
    vox_println_str(vox_str_concat(vox_str_new("Arquivo criado? "), vox_bool_to_str(vox_file_exists(arquivo_exemplo))));
    vox_str* conteudo_lido = vox_file_read(arquivo_exemplo);
    vox_println_str(vox_str_concat(vox_str_new("Conteudo lido do disco:\n"), conteudo_lido));
    vox_file_delete(arquivo_exemplo);
    vox_println_str(vox_str_concat(vox_str_new("Arquivo removido? Existe ainda? "), vox_bool_to_str(vox_file_exists(arquivo_exemplo))));
    vox_println_str(vox_str_new(""));
    vox_println_str(vox_str_new("--- 4. Data, Hora & Sleep Real ---"));
    vox_int agora = vox_time_now();
    vox_int agora_ms = vox_time_millis();
    vox_str* data_formatada = vox_time_format(agora, vox_str_new("YYYY-MM-DD HH:mm:ss"));
    vox_println_str(vox_str_concat(vox_str_new("Timestamp atual (s):  "), vox_int_to_str(agora)));
    vox_println_str(vox_str_concat(vox_str_new("Timestamp atual (ms): "), vox_int_to_str(agora_ms)));
    vox_println_str(vox_str_concat(vox_str_new("Data formatada:       "), data_formatada));
    vox_println_str(vox_str_new("Pausa de 50ms..."));
    vox_sleep(((vox_int)50LL));
    vox_println_str(vox_str_new("Pausa concluida!"));
    vox_println_str(vox_str_new(""));
    vox_println_str(vox_str_new("--- 5. Serializacao e Desserializacao JSON ---"));
    vox_str* json_texto = vox_str_new("{\"nome\": \"Vox\", \"versao\": \"1.1\", \"sucesso\": true}");
    vox_map* objeto_vox = vox_json_parse(json_texto);
    vox_println_str(vox_str_concat(vox_str_concat(vox_str_concat(vox_str_new("JSON parseado -> Nome: "), (vox_str*)vox_map_get((vox_map*)objeto_vox, vox_str_new("nome"))), vox_str_new(" | Versao: ")), (vox_str*)vox_map_get((vox_map*)objeto_vox, vox_str_new("versao"))));
    vox_str* serializado = vox_json_stringify((void*)(intptr_t)objeto_vox);
    vox_println_str(vox_str_concat(vox_str_new("Serializado de volta: "), serializado));
    vox_println_str(vox_str_new(""));
    vox_println_str(vox_str_new("--- 6. Expressoes Regulares (Regex) ---"));
    vox_str* email = vox_str_new("contato@voxlang.org");
    vox_bool email_valido = vox_regex_test(vox_str_new("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"), email);
    vox_println_str(vox_str_concat(vox_str_concat(vox_str_concat(vox_str_new("Email '"), email), vox_str_new("' e valido? ")), vox_bool_to_str(email_valido)));
    vox_str* frase = vox_str_new("A versao antiga era v1.0. Nova versao disponivel!");
    vox_str* frase_atualizada = vox_regex_replace(vox_str_new("v1\\.0"), frase, vox_str_new("v1.1"));
    vox_println_str(vox_str_concat(vox_str_new("Regex Replace: "), frase_atualizada));
    vox_println_str(vox_str_new(""));
    vox_println_str(vox_str_new("--- 7. Colecao Set (Conjuntos) ---"));
    vox_set* conjunto = vox_set_new();
    vox_set_add(conjunto, (void*)(intptr_t)vox_str_new("TypeScript"));
    vox_set_add(conjunto, (void*)(intptr_t)vox_str_new("C99"));
    vox_set_add(conjunto, (void*)(intptr_t)vox_str_new("Vox"));
    vox_set_add(conjunto, (void*)(intptr_t)vox_str_new("Vox"));
    vox_println_str(vox_str_concat(vox_str_new("Tamanho do conjunto (deve ser 3): "), vox_int_to_str(vox_set_size(conjunto))));
    vox_println_str(vox_str_concat(vox_str_new("Possui 'Vox'? "), vox_bool_to_str(vox_set_has(conjunto, (void*)(intptr_t)vox_str_new("Vox")))));
    vox_println_str(vox_str_concat(vox_str_new("Possui 'Python'? "), vox_bool_to_str(vox_set_has(conjunto, (void*)(intptr_t)vox_str_new("Python")))));
    vox_println_str(vox_str_concat(vox_str_new("Conteudo: "), vox_set_to_str(conjunto)));
    vox_println_str(vox_str_new(""));
    vox_println_str(vox_str_new("--- 8. Threads Reais & Mutex ---"));
    vox_thread_t* t1 = vox_thread_spawn_n((void*)tarefa_paralela, 2, (intptr_t)((vox_int)1LL), (intptr_t)((vox_int)100LL));
    vox_thread_t* t2 = vox_thread_spawn_n((void*)tarefa_paralela, 2, (intptr_t)((vox_int)2LL), (intptr_t)((vox_int)200LL));
    vox_int r1 = vox_thread_join((vox_thread_t*)t1);
    vox_int r2 = vox_thread_join((vox_thread_t*)t2);
    vox_println_str(vox_str_concat(vox_str_new("Resultado da Thread 1: "), vox_int_to_str(r1)));
    vox_println_str(vox_str_concat(vox_str_new("Resultado da Thread 2: "), vox_int_to_str(r2)));
    vox_mutex_t* trava = vox_mutex_new();
    vox_println_str(vox_str_concat(vox_str_new("Mutex criado: "), vox_mutex_to_str(trava)));
    vox_mutex_lock(trava);
    vox_println_str(vox_str_concat(vox_str_concat(vox_str_new("Secao critica protegida por Mutex (Thread ID: "), vox_int_to_str(vox_thread_id())), vox_str_new(")")));
    vox_mutex_unlock(trava);
    vox_println_str(vox_str_new("Mutex liberado com sucesso!"));
    vox_println_str(vox_str_new(""));
    vox_println_str(vox_str_new("================================================="));
    vox_println_str(vox_str_new("  🪐 TODOS OS RECURSOS v1.1 VALIDADOS COM SUCESSO!"));
    vox_println_str(vox_str_new("================================================="));
    return 0;
}