// ============================================================
// c_generator.ts — Transpiler / Gerador de Código C para Vox v1.0
// Suporta: struct, trait, impl, Option<T>, ??, move semantics, RAII
// Emite código ANSI/ISO C99 limpo e de alta performance
// ============================================================

import {
  ASTNode, NodeKind, ProgramNode, VarDeclNode, FnDeclNode,
  ClassDeclNode, BlockNode, ExprNode, ExprStmtNode,
  ReturnStmtNode, IfStmtNode, WhileStmtNode, ForStmtNode,
  MatchStmtNode, BinaryExprNode, UnaryExprNode, CallExprNode,
  MemberExprNode, IndexExprNode, IdentifierNode,
  AssignExprNode, NewExprNode, MethodDeclNode, FieldDeclNode,
  TypeNode, TypeRefNode, GenericTypeNode, MatchArmNode,
  StructDeclNode, StructFieldParam, ImplDeclNode,
  CoalesceExprNode, OwnershipExprNode,
} from '../parser/ast';

// ── Registry for struct definitions ──────────────────────────
interface StructInfo {
  name: string;
  fields: StructFieldParam[];
  generics: string[];
}

interface DropScopeVar {
  name: string;
  cType: string;
  isMoved: boolean;
}

interface DropScope {
  vars: DropScopeVar[];
}

export class CGenerator {
  private indentLevel: number = 0;
  private headerCode: string[] = [];
  private typedefs: string[] = [];
  private structDefs: string[] = [];
  private dropFns: string[] = [];
  private functionPrototypes: string[] = [];
  private functionDefs: string[] = [];
  private mainStatements: string[] = [];

  private classMap: Map<string, ClassDeclNode> = new Map();
  private structMap: Map<string, StructInfo> = new Map();
  private fnMap: Map<string, FnDeclNode> = new Map();
  private varTypeMap: Map<string, string> = new Map();
  private movedVars: Set<string> = new Set();
  private tempVarCounter: number = 0;

  // RAII: stack of drop-scopes
  private dropScopeStack: DropScope[] = [];

  generate(program: ProgramNode): string {
    this.headerCode = [
      '// ============================================================',
      '// Generated by Vox v1.0 C99 Compiler',
      '// ============================================================',
      '',
      '#include "vox_runtime.h"',
      '',
    ];

    // 1st pass: collect declarations
    for (const node of program.body) {
      if (node.kind === NodeKind.ClassDecl) {
        const cls = node as ClassDeclNode;
        this.classMap.set(cls.name, cls);
      } else if (node.kind === NodeKind.StructDecl) {
        const s = node as StructDeclNode;
        this.structMap.set(s.name, { name: s.name, fields: s.params, generics: s.generics });
      } else if (node.kind === NodeKind.FnDecl) {
        this.fnMap.set((node as FnDeclNode).name, node as FnDeclNode);
      }
    }

    // 2nd pass: typedefs + struct/drop codegen
    for (const [name] of this.classMap) {
      this.typedefs.push(`typedef struct Vox_${name} Vox_${name};`);
    }
    for (const [name] of this.structMap) {
      this.typedefs.push(`typedef struct Vox_${name} Vox_${name};`);
    }
    for (const [, cls] of this.classMap) {
      this.generateClassStruct(cls);
      this.generateDropFn(`Vox_${cls.name}`, 'heap');
    }
    for (const [, info] of this.structMap) {
      this.generateStructCDef(info);
      this.generateDropFn(`Vox_${info.name}`, 'stack');
    }

    // 3rd pass: methods, functions, top-level stmts
    for (const node of program.body) {
      switch (node.kind) {
        case NodeKind.ClassDecl:
          this.generateClassMethods(node as ClassDeclNode);
          break;
        case NodeKind.StructDecl:
          break; // handled above
        case NodeKind.TraitDecl:
          break; // purely semantic
        case NodeKind.ImplDecl:
          this.generateImplMethods(node as ImplDeclNode);
          break;
        case NodeKind.FnDecl:
          this.generateFunction(node as FnDeclNode);
          break;
        default:
          this.mainStatements.push(this.generateStmt(node));
          break;
      }
    }

    const mainFunc: string[] = [
      'int main(int argc, char** argv) {',
      '    (void)argc; (void)argv;',
      ...this.mainStatements.map(s => `    ${s}`),
      '    return 0;',
      '}',
    ];

    const parts: string[] = [
      this.headerCode.join('\n'),
      this.typedefs.length > 0 ? this.typedefs.join('\n') + '\n' : '',
      this.structDefs.length > 0 ? this.structDefs.join('\n\n') + '\n' : '',
      this.dropFns.length > 0 ? this.dropFns.join('\n\n') + '\n' : '',
      this.functionPrototypes.length > 0 ? this.functionPrototypes.join('\n') + '\n' : '',
      this.functionDefs.length > 0 ? this.functionDefs.join('\n\n') + '\n' : '',
      mainFunc.join('\n'),
    ];

    return parts.filter(p => p.length > 0).join('\n');
  }

  // ── RAII Scope Management ─────────────────────────────────

  private pushDropScope(): void {
    this.dropScopeStack.push({ vars: [] });
  }

  private popDropScope(): string[] {
    const scope = this.dropScopeStack.pop();
    if (!scope) return [];
    const drops: string[] = [];
    for (let i = scope.vars.length - 1; i >= 0; i--) {
      const v = scope.vars[i];
      if (!v.isMoved) {
        drops.push(`/* drop */ Vox_${v.cType}_drop(&${v.name});`);
      }
    }
    return drops;
  }

  private registerDropVar(name: string, cType: string): void {
    const top = this.dropScopeStack[this.dropScopeStack.length - 1];
    if (top && this.isStackStructType(cType)) {
      top.vars.push({ name, cType, isMoved: false });
    }
  }

  private markMoved(name: string): void {
    this.movedVars.add(name);
    for (let i = this.dropScopeStack.length - 1; i >= 0; i--) {
      const v = this.dropScopeStack[i].vars.find(v => v.name === name);
      if (v) { v.isMoved = true; break; }
    }
  }

  private isStackStructType(cType: string): boolean {
    return cType.startsWith('Vox_') && !cType.endsWith('*');
  }

  private collectDropsBeforeReturn(): string[] {
    const result: string[] = [];
    for (let i = this.dropScopeStack.length - 1; i >= 0; i--) {
      const scope = this.dropScopeStack[i];
      for (let j = scope.vars.length - 1; j >= 0; j--) {
        const v = scope.vars[j];
        if (!v.isMoved) result.push(`Vox_${v.cType}_drop(&${v.name});`);
      }
    }
    return result;
  }

  // ── Drop function generation ──────────────────────────────

  private generateDropFn(cTypeName: string, alloc: 'heap' | 'stack'): void {
    if (alloc === 'heap') {
      this.dropFns.push(
        `static inline void ${cTypeName}_drop(${cTypeName}** p) {\n` +
        `    if (p && *p) { free(*p); *p = NULL; }\n` +
        `}`
      );
    } else {
      this.dropFns.push(
        `static inline void ${cTypeName}_drop(${cTypeName}* p) {\n` +
        `    if (p) { memset(p, 0, sizeof(${cTypeName})); }\n` +
        `}`
      );
    }
  }

  // ── Struct C definition ───────────────────────────────────

  private generateStructCDef(info: StructInfo): void {
    const fields = info.fields.map(f => `    ${this.mapType(f.typeAnnot)} ${f.name};`);
    if (fields.length === 0) fields.push('    char _dummy;');
    this.structDefs.push(`struct Vox_${info.name} {\n${fields.join('\n')}\n};`);

    const paramList = info.fields.map(f => `${this.mapType(f.typeAnnot)} ${f.name}`).join(', ');
    const assignments = info.fields.map(f => `    _self.${f.name} = ${f.name};`).join('\n');

    this.functionPrototypes.push(`Vox_${info.name} Vox_${info.name}_new(${paramList});`);
    this.functionDefs.push(
      `Vox_${info.name} Vox_${info.name}_new(${paramList}) {\n` +
      `    Vox_${info.name} _self;\n` +
      `    memset(&_self, 0, sizeof(Vox_${info.name}));\n` +
      (assignments ? assignments + '\n' : '') +
      `    return _self;\n}`
    );
  }

  // ── Class codegen ─────────────────────────────────────────

  private generateClassStruct(cls: ClassDeclNode): void {
    const fields: string[] = [];
    if (cls.superClass) {
      const parent = this.classMap.get(cls.superClass);
      if (parent) {
        for (const m of parent.members) {
          if (m.kind === NodeKind.FieldDecl && !(m as FieldDeclNode).isStatic) {
            const f = m as FieldDeclNode;
            fields.push(`    ${this.mapType(f.typeAnnot)} ${f.name};`);
          }
        }
      }
    }
    for (const m of cls.members) {
      if (m.kind === NodeKind.FieldDecl && !(m as FieldDeclNode).isStatic) {
        const f = m as FieldDeclNode;
        fields.push(`    ${this.mapType(f.typeAnnot)} ${f.name};`);
      }
    }
    if (fields.length === 0) fields.push('    char _dummy;');
    this.structDefs.push(`struct Vox_${cls.name} {\n${fields.join('\n')}\n};`);
  }

  private generateClassMethods(cls: ClassDeclNode): void {
    const ctorName = `Vox_${cls.name}_new`;
    const ctorMember = cls.members.find(m => m.kind === NodeKind.ConstructorDecl);
    let ctorParams = '';

    if (ctorMember && (ctorMember as any).params) {
      ctorParams = (ctorMember as any).params
        .map((p: any) => `${this.mapType(p.typeAnnot)} ${p.name}`).join(', ');
    }

    this.functionPrototypes.push(`Vox_${cls.name}* ${ctorName}(${ctorParams});`);

    const ctorBody: string[] = [
      `Vox_${cls.name}* ${ctorName}(${ctorParams}) {`,
      `    Vox_${cls.name}* self = (Vox_${cls.name}*)calloc(1, sizeof(Vox_${cls.name}));`,
    ];

    for (const m of cls.members) {
      if (m.kind === NodeKind.FieldDecl && !(m as FieldDeclNode).isStatic) {
        const f = m as FieldDeclNode;
        if (f.value) ctorBody.push(`    self->${f.name} = ${this.generateExpr(f.value)};`);
      }
    }

    if (ctorMember && (ctorMember as any).body) {
      this.pushDropScope();
      for (const stmt of (ctorMember as any).body.body) {
        ctorBody.push(`    ${this.generateStmt(stmt)}`);
      }
      this.popDropScope().forEach(d => ctorBody.push(`    ${d}`));
    }

    ctorBody.push('    return self;');
    ctorBody.push('}');
    this.functionDefs.push(ctorBody.join('\n'));

    for (const m of cls.members) {
      if (m.kind === NodeKind.MethodDecl) {
        this.generateMethodDef(`Vox_${cls.name}`, m as MethodDeclNode);
      }
    }
  }

  // ── Impl block ────────────────────────────────────────────

  private generateImplMethods(impl: ImplDeclNode): void {
    for (const method of impl.methods) {
      this.generateMethodDef(`Vox_${impl.targetType}`, method);
    }
  }

  private generateMethodDef(cTypeName: string, m: MethodDeclNode): void {
    const retType = this.mapType(m.returnType);
    const methodName = `${cTypeName}_${m.name}`;

    const paramsList: string[] = [];
    if (!m.isStatic) paramsList.push(`${cTypeName}* self`);
    for (const p of m.params) {
      if (p.name !== 'self') paramsList.push(`${this.mapType(p.typeAnnot)} ${p.name}`);
    }

    const paramStr = paramsList.join(', ');
    this.functionPrototypes.push(`${retType} ${methodName}(${paramStr});`);

    const code: string[] = [`${retType} ${methodName}(${paramStr}) {`];
    this.pushDropScope();
    if (m.body.kind === NodeKind.Block) {
      for (const stmt of (m.body as BlockNode).body) code.push(`    ${this.generateStmt(stmt)}`);
    } else {
      code.push(`    return ${this.generateExpr(m.body as ExprNode)};`);
    }
    this.popDropScope().forEach(d => code.push(`    ${d}`));
    code.push('}');
    this.functionDefs.push(code.join('\n'));
  }

  // ── Top-level function ────────────────────────────────────

  private generateFunction(fn: FnDeclNode): void {
    const cFnName = fn.name === 'main' ? 'Vox_user_main' : fn.name;
    const retType = this.mapType(fn.returnType);
    const params = fn.params.map(p => `${this.mapType(p.typeAnnot)} ${p.name}`).join(', ');

    this.functionPrototypes.push(`${retType} ${cFnName}(${params});`);
    const code: string[] = [`${retType} ${cFnName}(${params}) {`];
    this.pushDropScope();
    if (fn.body.kind === NodeKind.Block) {
      for (const stmt of (fn.body as BlockNode).body) code.push(`    ${this.generateStmt(stmt)}`);
    } else {
      code.push(`    return ${this.generateExpr(fn.body as ExprNode)};`);
    }
    this.popDropScope().forEach(d => code.push(`    ${d}`));
    code.push('}');
    this.functionDefs.push(code.join('\n'));
  }

  // ── Statement generation ──────────────────────────────────

  private generateStmt(node: ASTNode): string {
    switch (node.kind) {
      case NodeKind.VarDecl: {
        const v = node as VarDeclNode;
        const type = v.typeAnnot
          ? this.mapType(v.typeAnnot)
          : (v.value ? this.inferExprType(v.value) : 'vox_int');
        this.varTypeMap.set(v.name, type);

        if (v.value && v.value.kind === NodeKind.OwnershipExpr) {
          const ownExpr = v.value as OwnershipExprNode;
          if (ownExpr.ownership === 'own' && ownExpr.operand.kind === NodeKind.Identifier) {
            this.markMoved((ownExpr.operand as IdentifierNode).name);
          }
        }
        this.registerDropVar(v.name, type);

        if (v.value) {
          const valExpr = this.generateExpr(v.value);
          return `${type} ${v.name} = ${valExpr};`;
        }
        if (this.isStackStructType(type)) {
          return `${type} ${v.name}; memset(&${v.name}, 0, sizeof(${type}));`;
        }
        return `${type} ${v.name} = 0;`;
      }

      case NodeKind.ExprStmt:
        return `${this.generateExpr((node as ExprStmtNode).expr)};`;

      case NodeKind.ReturnStmt: {
        const r = node as ReturnStmtNode;
        const drops = this.collectDropsBeforeReturn();
        const dropStr = drops.length > 0 ? drops.join(' ') + ' ' : '';
        if (r.value) return `${dropStr}return ${this.generateExpr(r.value)};`;
        return `${dropStr}return;`;
      }

      case NodeKind.IfStmt: {
        const ifNode = node as IfStmtNode;
        const parts: string[] = [`if (${this.generateExpr(ifNode.condition)}) {`];
        this.pushDropScope();
        for (const s of ifNode.then.body) parts.push(`    ${this.generateStmt(s)}`);
        this.popDropScope().forEach(d => parts.push(`    ${d}`));
        parts.push('}');
        for (const elif of ifNode.elif) {
          parts.push(`else if (${this.generateExpr(elif.condition)}) {`);
          this.pushDropScope();
          for (const s of elif.block.body) parts.push(`    ${this.generateStmt(s)}`);
          this.popDropScope().forEach(d => parts.push(`    ${d}`));
          parts.push('}');
        }
        if (ifNode.else) {
          parts.push('else {');
          this.pushDropScope();
          for (const s of ifNode.else.body) parts.push(`    ${this.generateStmt(s)}`);
          this.popDropScope().forEach(d => parts.push(`    ${d}`));
          parts.push('}');
        }
        return parts.join('\n');
      }

      case NodeKind.WhileStmt: {
        const w = node as WhileStmtNode;
        const parts: string[] = [`while (${this.generateExpr(w.condition)}) {`];
        this.pushDropScope();
        for (const s of w.body.body) parts.push(`    ${this.generateStmt(s)}`);
        this.popDropScope().forEach(d => parts.push(`    ${d}`));
        parts.push('}');
        return parts.join('\n');
      }

      case NodeKind.ForStmt: {
        const f = node as ForStmtNode;
        const idxVar = `_i_${this.tempVarCounter++}`;
        const arrVar = `_arr_${this.tempVarCounter++}`;
        const arrExpr = this.generateExpr(f.iterable);
        const parts: string[] = [
          `vox_array* ${arrVar} = ${arrExpr};`,
          `for (size_t ${idxVar} = 0; ${idxVar} < vox_array_len(${arrVar}); ${idxVar}++) {`,
          `    void* ${f.variable} = vox_array_get(${arrVar}, ${idxVar});`,
        ];
        this.pushDropScope();
        for (const s of f.body.body) parts.push(`    ${this.generateStmt(s)}`);
        this.popDropScope().forEach(d => parts.push(`    ${d}`));
        parts.push('}');
        return parts.join('\n');
      }

      case NodeKind.BreakStmt:    return 'break;';
      case NodeKind.ContinueStmt: return 'continue;';

      case NodeKind.SpawnStmt: {
        const s = node as any;
        const parts = ['{'];
        this.pushDropScope();
        for (const stmt of s.body.body) parts.push(`    ${this.generateStmt(stmt)}`);
        this.popDropScope().forEach(d => parts.push(`    ${d}`));
        parts.push('}');
        return parts.join('\n');
      }

      case NodeKind.TryCatchStmt: {
        const tc = node as any;
        const frameVar = `_vox_frame_${this.tempVarCounter++}`;
        const parts = [
          `{`,
          `    vox_exception_frame ${frameVar};`,
          `    vox_push_try_frame(&${frameVar});`,
          `    if (setjmp(${frameVar}.jmp) == 0) {`,
        ];
        this.pushDropScope();
        for (const s of tc.tryBlock.body) parts.push(`        ${this.generateStmt(s)}`);
        this.popDropScope().forEach(d => parts.push(`        ${d}`));
        parts.push(`        vox_pop_try_frame();`);
        parts.push(`    } else {`);
        parts.push(`        vox_pop_try_frame();`);
        if (tc.catchBlock) {
          if (tc.catchParam) {
            this.varTypeMap.set(tc.catchParam, 'vox_str*');
            parts.push(`        vox_str* ${tc.catchParam} = (vox_str*)${frameVar}.thrown_val;`);
          }
          this.pushDropScope();
          for (const s of tc.catchBlock.body) parts.push(`        ${this.generateStmt(s)}`);
          this.popDropScope().forEach(d => parts.push(`        ${d}`));
        }
        parts.push(`    }`);
        if (tc.finallyBlock) {
          parts.push(`    {`);
          this.pushDropScope();
          for (const s of tc.finallyBlock.body) parts.push(`        ${this.generateStmt(s)}`);
          this.popDropScope().forEach(d => parts.push(`        ${d}`));
          parts.push(`    }`);
        }
        parts.push(`}`);
        return parts.join('\n');
      }

      case NodeKind.ThrowStmt: {
        const th = node as any;
        return `vox_throw((void*)(intptr_t)${this.generateExpr(th.value)});`;
      }

      case NodeKind.StructDecl:
      case NodeKind.TraitDecl:
      case NodeKind.ImplDecl:
        return '';

      default:
        return `// Unsupported stmt kind: ${node.kind}`;
    }
  }

  // ── Expression generation ─────────────────────────────────

  private generateExpr(node: ExprNode): string {
    switch (node.kind) {
      case NodeKind.IntLiteral:    return `((vox_int)${(node as any).value}LL)`;
      case NodeKind.FloatLiteral:  return `((vox_float)${(node as any).value})`;
      case NodeKind.BoolLiteral:   return (node as any).value ? 'true' : 'false';
      case NodeKind.CharLiteral:   return `'${(node as any).value}'`;
      case NodeKind.StringLiteral: return `vox_str_new(${JSON.stringify((node as any).value as string)})`;

      case NodeKind.Identifier: {
        const id = (node as IdentifierNode).name;
        if (id === 'self') return 'self';
        if (id === 'none') return 'vox_none()';
        return id;
      }

      case NodeKind.OwnershipExpr: {
        const o = node as OwnershipExprNode;
        if (o.ownership === 'own' && o.operand.kind === NodeKind.Identifier) {
          this.markMoved((o.operand as IdentifierNode).name);
        }
        return this.generateExpr(o.operand);
      }

      case NodeKind.CoalesceExpr: {
        const c = node as CoalesceExprNode;
        const lExpr = this.generateExpr(c.left);
        const rExpr = this.generateExpr(c.right);
        const tmp = `_coalesce_${this.tempVarCounter++}`;
        return `({ vox_option ${tmp} = ${lExpr}; ${tmp}.is_some ? (intptr_t)${tmp}.value : (intptr_t)(${rExpr}); })`;
      }

      case NodeKind.BinaryExpr: {
        const b = node as BinaryExprNode;
        const left = this.generateExpr(b.left);
        const right = this.generateExpr(b.right);
        if (b.operator === '+' && (this.isLikelyString(b.left) || this.isLikelyString(b.right))) {
          return `vox_str_concat(${this.toStrExpr(b.left, left)}, ${this.toStrExpr(b.right, right)})`;
        }
        if (b.operator === '==' && (this.isLikelyString(b.left) || this.isLikelyString(b.right))) {
          return `vox_str_eq(${left}, ${right})`;
        }
        if (b.operator === '!=' && (this.isLikelyString(b.left) || this.isLikelyString(b.right))) {
          return `(!vox_str_eq(${left}, ${right}))`;
        }
        return `(${left} ${b.operator} ${right})`;
      }

      case NodeKind.UnaryExpr: {
        const u = node as UnaryExprNode;
        return `(${u.operator}${this.generateExpr(u.operand)})`;
      }

      case NodeKind.AssignExpr: {
        const a = node as AssignExprNode;
        return `${this.generateExpr(a.target)} ${a.operator} ${this.generateExpr(a.value)}`;
      }

      case NodeKind.CallExpr: {
        const c = node as CallExprNode;

        if (c.callee.kind === NodeKind.MemberExpr) {
          const m = c.callee as MemberExprNode;
          const obj = this.generateExpr(m.object);

          // ── Class/struct method dispatch has priority over builtins ──
          const className = this.guessClassName(m.object);
          if (className && (this.classMap.has(className) || this.structMap.has(className))) {
            const args = [obj, ...c.args.map(a => this.generateExpr(a))].join(', ');
            return `Vox_${className}_${m.property}(${args})`;
          }

          // ── Array builtins ────────────────────────────────────────────
          if (m.property === 'push' && c.args.length > 0) return `vox_array_push(${obj}, (void*)(intptr_t)${this.generateExpr(c.args[0])})`;
          if (m.property === 'pop')  return `vox_array_pop(${obj})`;
          if (m.property === 'get' && c.args.length > 0)  return `vox_array_get(${obj}, (size_t)${this.generateExpr(c.args[0])})`;

          // ── Channel builtins ──────────────────────────────────────────
          if (m.property === 'send' && c.args.length > 0) {
            const arg = c.args[0];
            if (arg.kind === NodeKind.OwnershipExpr && (arg as OwnershipExprNode).operand.kind === NodeKind.Identifier) {
              this.markMoved(((arg as OwnershipExprNode).operand as IdentifierNode).name);
            }
            return `vox_chan_send(${obj}, (void*)(intptr_t)${this.generateExpr(arg)})`;
          }
          if (m.property === 'recv')  return `(intptr_t)vox_chan_recv(${obj})`;
          if (m.property === 'close') return `vox_chan_close(${obj})`;

          // ── Option builtins ───────────────────────────────────────────
          if (m.property === 'unwrap') return `vox_unwrap(${obj})`;
          if (m.property === 'is_some') return `(${obj}.is_some)`;
          if (m.property === 'is_none') return `(!(${obj}.is_some))`;
          if (m.property === 'unwrap_or' && c.args.length > 0) {
            const tmp = `_opt_${this.tempVarCounter++}`;
            const fb = this.generateExpr(c.args[0]);
            return `({ vox_option ${tmp} = ${obj}; ${tmp}.is_some ? (intptr_t)${tmp}.value : (intptr_t)(${fb}); })`;
          }

          const fallbackArgs = c.args.map(a => this.generateExpr(a)).join(', ');
          return `${obj}->${m.property}(${fallbackArgs})`;
        }

        if (c.callee.kind === NodeKind.Identifier) {
          const name = (c.callee as IdentifierNode).name;
          if (name === 'println') return this.genPrint(c, true);
          if (name === 'print')   return this.genPrint(c, false);

          const args = c.args.map(a => this.generateExpr(a)).join(', ');

          if (name === 'main')      return `Vox_user_main(${args})`;
          if (name === 'int')       return `((vox_int)${this.generateExpr(c.args[0])})`;
          if (name === 'float')     return `((vox_float)${this.generateExpr(c.args[0])})`;
          if (name === 'bool')      return `((vox_bool)(${this.generateExpr(c.args[0])}))`;
          if (name === 'str')       return this.genToStr(c.args[0]);
          if (name === 'len')       return `((vox_int)vox_array_len((vox_array*)${this.generateExpr(c.args[0])}))`;
          if (name === 'chan_new')   return `vox_chan_new(${c.args.length > 0 ? this.generateExpr(c.args[0]) : '16'})`;
          if (name === 'chan_send')  return `vox_chan_send(${this.generateExpr(c.args[0])}, (void*)(intptr_t)${this.generateExpr(c.args[1])})`;
          if (name === 'chan_recv')  return `(intptr_t)vox_chan_recv(${this.generateExpr(c.args[0])})`;
          if (name === 'chan_close') return `vox_chan_close(${this.generateExpr(c.args[0])})`;
          if (name === 'file_read')   return `vox_file_read(${this.generateExpr(c.args[0])})`;
          if (name === 'file_write')  return `vox_file_write(${this.generateExpr(c.args[0])}, ${this.generateExpr(c.args[1])})`;
          if (name === 'file_append') return `vox_file_append(${this.generateExpr(c.args[0])}, ${this.generateExpr(c.args[1])})`;
          if (name === 'file_exists') return `vox_file_exists(${this.generateExpr(c.args[0])})`;
          if (name === 'file_delete') return `vox_file_delete(${this.generateExpr(c.args[0])})`;
          if (name === 'dir_list')    return `vox_dir_list(${this.generateExpr(c.args[0])})`;
          if (name === 'dir_create')  return `vox_dir_create(${this.generateExpr(c.args[0])})`;
          if (name === 'time_now')    return 'vox_time_now()';
          if (name === 'time_millis') return 'vox_time_millis()';
          if (name === 'time_format') return `vox_time_format(${this.generateExpr(c.args[0])}, ${this.generateExpr(c.args[1])})`;
          if (name === 'sleep')       return `vox_sleep(${this.generateExpr(c.args[0])})`;
          if (name === 'http_get')    return `vox_http_get(${this.generateExpr(c.args[0])})`;
          if (name === 'http_post')   return `vox_http_post(${this.generateExpr(c.args[0])}, ${this.generateExpr(c.args[1])})`;
          if (name === 'json_parse')  return `vox_json_parse(${this.generateExpr(c.args[0])})`;
          if (name === 'json_stringify') return `vox_json_stringify((void*)(intptr_t)${this.generateExpr(c.args[0])})`;
          if (name === 'regex_test')  return `vox_regex_test(${this.generateExpr(c.args[0])}, ${this.generateExpr(c.args[1])})`;
          if (name === 'regex_match') return `vox_regex_match(${this.generateExpr(c.args[0])}, ${this.generateExpr(c.args[1])})`;
          if (name === 'regex_replace') return `vox_regex_replace(${this.generateExpr(c.args[0])}, ${this.generateExpr(c.args[1])}, ${this.generateExpr(c.args[2])})`;
          if (name === 'set_new')     return 'vox_set_new()';
          if (name === 'set_add')     return `vox_set_add(${this.generateExpr(c.args[0])}, (void*)(intptr_t)${this.generateExpr(c.args[1])})`;
          if (name === 'set_has')     return `vox_set_has(${this.generateExpr(c.args[0])}, (void*)(intptr_t)${this.generateExpr(c.args[1])})`;
          if (name === 'set_delete')  return `vox_set_delete(${this.generateExpr(c.args[0])}, (void*)(intptr_t)${this.generateExpr(c.args[1])})`;
          if (name === 'set_size')    return `vox_set_size(${this.generateExpr(c.args[0])})`;
          if (name === 'set_to_array') return `vox_set_to_array(${this.generateExpr(c.args[0])})`;
          if (name === 'thread_spawn') {
            const fnArg = this.generateExpr(c.args[0]);
            const extraArgs = c.args.slice(1).map(a => `(intptr_t)${this.generateExpr(a)}`);
            const count = extraArgs.length;
            return `vox_thread_spawn_n((void*)${fnArg}, ${count}${count > 0 ? ', ' + extraArgs.join(', ') : ''})`;
          }
          if (name === 'thread_join') return `vox_thread_join((vox_thread_t*)${this.generateExpr(c.args[0])})`;
          if (name === 'thread_id')   return 'vox_thread_id()';
          if (name === 'mutex_new')   return 'vox_mutex_new()';
          if (name === 'mutex_lock')  return `vox_mutex_lock(${this.generateExpr(c.args[0])})`;
          if (name === 'mutex_unlock') return `vox_mutex_unlock(${this.generateExpr(c.args[0])})`;
          if (name === 'some')      return `vox_some((void*)(intptr_t)${this.generateExpr(c.args[0])})`;
          if (name === 'none')      return 'vox_none()';
          if (name === 'ok')        return `vox_ok((void*)(intptr_t)${this.generateExpr(c.args[0])})`;
          if (name === 'err')       return `vox_err((void*)(intptr_t)${this.generateExpr(c.args[0])})`;
          if (name === 'sqrt')      return `sqrt(${this.generateExpr(c.args[0])})`;
          if (name === 'abs')       return `fabs(${this.generateExpr(c.args[0])})`;
          if (this.structMap.has(name)) return `Vox_${name}_new(${args})`;

          return `${name}(${args})`;
        }

        const args = c.args.map(a => this.generateExpr(a)).join(', ');
        return `${this.generateExpr(c.callee)}(${args})`;
      }

      case NodeKind.MemberExpr: {
        const m = node as MemberExprNode;
        const obj = this.generateExpr(m.object);
        if (m.property === 'len')       return `vox_array_len(${obj})`;
        if (m.property === 'capacity')  return `(${obj}->capacity)`;
        if (m.property === 'is_closed') return `(${obj}->closed)`;
        const objType = this.inferExprType(m.object);
        if (this.isStackStructType(objType)) return `${obj}.${m.property}`;
        return `${obj}->${m.property}`;
      }

      case NodeKind.IndexExpr: {
        const idx = node as IndexExprNode;
        if (this.isLikelyString(idx.index)) {
          return `(vox_str*)vox_map_get((vox_map*)${this.generateExpr(idx.object)}, ${this.generateExpr(idx.index)})`;
        }
        return `(intptr_t)vox_array_get((vox_array*)${this.generateExpr(idx.object)}, (size_t)${this.generateExpr(idx.index)})`;
      }

      case NodeKind.NewExpr: {
        const n = node as NewExprNode;
        if (n.className === 'Channel') {
          return `vox_chan_new(${n.args.length > 0 ? this.generateExpr(n.args[0]) : '16'})`;
        }
        const args = n.args.map(a => this.generateExpr(a)).join(', ');
        return `Vox_${n.className}_new(${args})`;
      }

      case NodeKind.StructLiteral: {
        const sl = node as any;
        const info = this.structMap.get(sl.name);
        if (info) {
          const args = info.fields.map((f: StructFieldParam) => {
            const entry = (sl.fields as Array<{ key: string; value: ExprNode }>).find(e => e.key === f.name);
            return entry ? this.generateExpr(entry.value) : '0';
          }).join(', ');
          return `Vox_${sl.name}_new(${args})`;
        }
        return '/* unknown struct */0';
      }

      case NodeKind.ArrayLiteral: {
        const arr = node as any;
        const temp = `_arr_${this.tempVarCounter++}`;
        const items = (arr.elements as ExprNode[]).map(el =>
          `vox_array_push(${temp}, (void*)(intptr_t)${this.generateExpr(el)});`
        );
        return `({ vox_array* ${temp} = vox_array_new(${Math.max(arr.elements.length, 4)}); ${items.join(' ')} ${temp}; })`;
      }

      case NodeKind.PipeExpr: {
        const p = node as any;
        const left = this.generateExpr(p.left);
        if (p.right.kind === NodeKind.Identifier) {
          return `${(p.right as IdentifierNode).name}(${left})`;
        }
        return `${this.generateExpr(p.right)}(${left})`;
      }

      case NodeKind.AwaitExpr:
        return this.generateExpr((node as any).value);

      case NodeKind.TryPropagateExpr: {
        const innerExpr = (node as any).expr;
        const innerType = this.inferExprType(innerExpr);
        const temp = `_prop_${this.tempVarCounter++}`;
        if (innerType === 'vox_result') {
          return `({ vox_result ${temp} = ${this.generateExpr(innerExpr)}; if (!${temp}.is_ok) return vox_err(${temp}.value); ${temp}.value; })`;
        }
        return `({ vox_option ${temp} = ${this.generateExpr(innerExpr)}; if (!${temp}.is_some) return vox_none(); ${temp}.value; })`;
      }

      case NodeKind.MacroCall:
        return this.generateMacro(node as any);

      case NodeKind.MatchStmt:
        return this.generateMatchExpr(node as MatchStmtNode);

      default:
        return '0';
    }
  }

  // ── Macro codegen ─────────────────────────────────────────

  private generateMacro(m: any): string {
    if (m.name === 'format!') {
      if (m.args.length === 0) return 'vox_str_new("")';
      const tpl: string = m.args[0].kind === NodeKind.StringLiteral ? m.args[0].value : '%s';
      let cFmt = '', remaining = tpl;
      const fmtArgs: string[] = [];
      for (let i = 1; i < m.args.length; i++) {
        const idx = remaining.indexOf('{}');
        if (idx < 0) break;
        cFmt += remaining.slice(0, idx);
        const a = m.args[i];
        if (this.isLikelyString(a)) { cFmt += '%s'; fmtArgs.push(`${this.generateExpr(a)}->data`); }
        else if (this.isLikelyFloat(a)) { cFmt += '%g'; fmtArgs.push(`(double)${this.generateExpr(a)}`); }
        else { cFmt += '%lld'; fmtArgs.push(`(long long)${this.generateExpr(a)}`); }
        remaining = remaining.slice(idx + 2);
      }
      cFmt += remaining;
      const as2 = fmtArgs.length > 0 ? `, ${fmtArgs.join(', ')}` : '';
      return `vox_str_format(${JSON.stringify(cFmt)}${as2})`;
    }
    if (m.name === 'assert!') {
      const cond = this.generateExpr(m.args[0]);
      const msg = m.args.length > 1 ? JSON.stringify(m.args[1].value ?? 'assertion failed') : '"assertion failed"';
      return `vox_assert(${cond}, ${msg})`;
    }
    if (m.name === 'dbg!') {
      const val = this.generateExpr(m.args[0]);
      return `(printf("[dbg!] %lld\\n", (long long)${val}), ${val})`;
    }
    if (m.name === 'panic!') {
      const msg = m.args.length > 0 ? JSON.stringify(m.args[0].value ?? 'panic') : '"panic"';
      return `vox_panic(${msg})`;
    }
    return '0';
  }

  // ── Match expression ──────────────────────────────────────

  private generateMatchExpr(match: MatchStmtNode): string {
    const valExpr = this.generateExpr(match.value);
    const valType = this.inferExprType(match.value);
    const tempVal = `_match_val_${this.tempVarCounter++}`;
    const isOption = valType === 'vox_option';
    const tempType = isOption ? 'vox_option' : (valType === 'vox_result' ? 'vox_result' : valType);

    const buildTernary = (armIndex: number): string => {
      if (armIndex >= match.arms.length) return '0';
      const arm = match.arms[armIndex];

      let armBodyExpr: ExprNode;
      if (arm.body.kind === NodeKind.Block) {
        const first = (arm.body as BlockNode).body[0];
        if (first?.kind === NodeKind.ExprStmt) armBodyExpr = (first as ExprStmtNode).expr;
        else if (first?.kind === NodeKind.ReturnStmt && (first as ReturnStmtNode).value) armBodyExpr = (first as ReturnStmtNode).value!;
        else armBodyExpr = first as any;
      } else {
        armBodyExpr = arm.body as ExprNode;
      }

      const armBody = this.generateExpr(armBodyExpr);
      const patt = arm.pattern;

      if (patt.kind === 'wildcard') return armBody;

      if (patt.kind === 'none') {
        const cond = `(!${tempVal}.is_some)${arm.guard ? ` && (${this.generateExpr(arm.guard)})` : ''}`;
        return `(${cond} ? (${armBody}) : ${buildTernary(armIndex + 1)})`;
      }

      if (patt.kind === 'some') {
        const bindName = (patt as any).name;
        const cond = `(${tempVal}.is_some)${arm.guard ? ` && (${this.generateExpr(arm.guard)})` : ''}`;
        const innerBody = `({ intptr_t ${bindName} = (intptr_t)${tempVal}.value; ${armBody}; })`;
        return `(${cond} ? ${innerBody} : ${buildTernary(armIndex + 1)})`;
      }

      if (patt.kind === 'ok') {
        const cond = `(${tempVal}.is_ok)${arm.guard ? ` && (${this.generateExpr(arm.guard)})` : ''}`;
        return `(${cond} ? (${armBody}) : ${buildTernary(armIndex + 1)})`;
      }

      if (patt.kind === 'err') {
        const cond = `(!(${tempVal}.is_ok))${arm.guard ? ` && (${this.generateExpr(arm.guard)})` : ''}`;
        return `(${cond} ? (${armBody}) : ${buildTernary(armIndex + 1)})`;
      }

      let cond = '';
      if (patt.kind === 'literal') cond = `(${tempVal} == ${this.generateExpr((patt as any).value)})`;
      else if (patt.kind === 'range') {
        const from = this.generateExpr((patt as any).from);
        const to = this.generateExpr((patt as any).to);
        cond = `(${tempVal} >= ${from} && ${tempVal} <= ${to})`;
      } else if (patt.kind === 'identifier') cond = 'true';
      else cond = 'false';

      if (arm.guard) cond += ` && (${this.generateExpr(arm.guard)})`;
      return `(${cond} ? (${armBody}) : ${buildTernary(armIndex + 1)})`;
    };

    return `({ ${tempType} ${tempVal} = ${valExpr}; ${buildTernary(0)}; })`;
  }

  // ── Type mapping ──────────────────────────────────────────

  private mapType(typeNode?: TypeNode): string {
    if (!typeNode) return 'vox_int';
    switch (typeNode.kind) {
      case NodeKind.TypeRef: {
        const name = (typeNode as TypeRefNode).name;
        switch (name) {
          case 'int':   return 'vox_int';
          case 'float': return 'vox_float';
          case 'bool':  return 'vox_bool';
          case 'char':  return 'vox_char';
          case 'str':   return 'vox_str*';
          case 'void':  return 'void';
          default:
            if (this.classMap.has(name))  return `Vox_${name}*`;
            if (this.structMap.has(name)) return `Vox_${name}`;
            return 'void*';
        }
      }
      case NodeKind.GenericType: {
        const g = typeNode as GenericTypeNode;
        if (g.base === 'Option')  return 'vox_option';
        if (g.base === 'Result')  return 'vox_result';
        if (g.base === 'Channel') return 'vox_channel*';
        if (g.base === 'Array')   return 'vox_array*';
        return 'void*';
      }
      case NodeKind.OptionType: return 'vox_option';
      case NodeKind.ResultType:  return 'vox_result';
      default:                   return 'vox_int';
    }
  }

  // ── Type inference ────────────────────────────────────────

  private inferExprType(node: ExprNode): string {
    switch (node.kind) {
      case NodeKind.IntLiteral:    return 'vox_int';
      case NodeKind.FloatLiteral:  return 'vox_float';
      case NodeKind.BoolLiteral:   return 'vox_bool';
      case NodeKind.CharLiteral:   return 'vox_char';
      case NodeKind.StringLiteral: return 'vox_str*';
      case NodeKind.ArrayLiteral:  return 'vox_array*';
      case NodeKind.NewExpr: {
        const n = node as NewExprNode;
        return this.structMap.has(n.className) ? `Vox_${n.className}` : `Vox_${n.className}*`;
      }
      case NodeKind.Identifier: {
        const id = (node as IdentifierNode).name;
        if (id === 'none') return 'vox_option';
        return this.varTypeMap.get(id) ?? 'vox_int';
      }
      case NodeKind.CallExpr: {
        const c = node as CallExprNode;
        if (c.callee.kind === NodeKind.Identifier) {
          const fn = (c.callee as IdentifierNode).name;
          if (fn === 'some' || fn === 'none') return 'vox_option';
          if (fn === 'ok' || fn === 'err')    return 'vox_result';
          if (fn === 'chan_new') return 'vox_channel*';
          if (fn === 'str')     return 'vox_str*';
          if (fn === 'int')     return 'vox_int';
          if (fn === 'float')   return 'vox_float';
          if (fn === 'bool')    return 'vox_bool';
          if (fn === 'len')     return 'vox_int';
          if (fn === 'file_read' || fn === 'http_get' || fn === 'http_post' || fn === 'time_format' || fn === 'json_stringify' || fn === 'regex_match' || fn === 'regex_replace') return 'vox_str*';
          if (fn === 'file_write' || fn === 'file_append' || fn === 'file_exists' || fn === 'file_delete' || fn === 'dir_create' || fn === 'regex_test' || fn === 'set_has') return 'vox_bool';
          if (fn === 'time_now' || fn === 'time_millis' || fn === 'thread_join' || fn === 'thread_id' || fn === 'set_size') return 'vox_int';
          if (fn === 'dir_list' || fn === 'set_to_array') return 'vox_array*';
          if (fn === 'json_parse') return 'vox_map*';
          if (fn === 'set_new') return 'vox_set*';
          if (fn === 'mutex_new') return 'vox_mutex_t*';
          if (fn === 'thread_spawn') return 'vox_thread_t*';
          if (this.structMap.has(fn)) return `Vox_${fn}`;
          const decl = this.fnMap.get(fn);
          if (decl?.returnType) return this.mapType(decl.returnType);
        }
        if (c.callee.kind === NodeKind.MemberExpr) {
          const m = c.callee as MemberExprNode;
          if (m.property === 'recv') return 'vox_int';
          if (m.property === 'unwrap' || m.property === 'unwrap_or') return 'vox_int';
          if (m.property === 'is_some' || m.property === 'is_none') return 'vox_bool';
          const cn = this.guessClassName(m.object);
          if (cn) { const rt = this.getMethodReturnType(cn, m.property); if (rt) return rt; }
        }
        return 'vox_int';
      }
      case NodeKind.MemberExpr: {
        const m = node as MemberExprNode;
        if (m.property === 'len') return 'vox_int';
        const objType = this.inferExprType(m.object);
        if (this.isStackStructType(objType)) {
          const sName = objType.slice(4);
          const info = this.structMap.get(sName);
          if (info) { const f = info.fields.find(f => f.name === m.property); if (f) return this.mapType(f.typeAnnot); }
        }
        const cn = this.guessClassName(m.object);
        if (cn) { const ft = this.getFieldType(cn, m.property); if (ft) return ft; }
        return 'vox_int';
      }
      case NodeKind.IndexExpr: {
        const idx = node as IndexExprNode;
        if (this.isLikelyString(idx.index)) return 'vox_str*';
        return 'vox_int';
      }
      case NodeKind.BinaryExpr: {
        const b = node as BinaryExprNode;
        if (b.operator === '+' && (this.isLikelyString(b.left) || this.isLikelyString(b.right))) return 'vox_str*';
        if (['==','!=','<','<=','>','>=','&&','||'].includes(b.operator)) return 'vox_bool';
        if (this.isLikelyFloat(b.left) || this.isLikelyFloat(b.right)) return 'vox_float';
        return 'vox_int';
      }
      case NodeKind.CoalesceExpr: return this.inferExprType((node as CoalesceExprNode).right);
      case NodeKind.MacroCall:    return (node as any).name === 'format!' ? 'vox_str*' : 'vox_int';
      case NodeKind.MatchStmt: {
        const match = node as MatchStmtNode;
        if (match.arms.length > 0) {
          const arm = match.arms[0];
          let expr: ExprNode | undefined;
          if (arm.body.kind === NodeKind.Block) {
            const f = (arm.body as BlockNode).body[0];
            if (f?.kind === NodeKind.ExprStmt) expr = (f as ExprStmtNode).expr;
            else if (f?.kind === NodeKind.ReturnStmt) expr = (f as ReturnStmtNode).value;
          } else { expr = arm.body as ExprNode; }
          if (expr) return this.inferExprType(expr);
        }
        return 'vox_int';
      }
      case NodeKind.TryPropagateExpr: {
        const inner = (node as any).expr;
        if (inner.kind === NodeKind.CallExpr && inner.callee.kind === NodeKind.Identifier) {
          const fnName = (inner.callee as IdentifierNode).name;
          const decl = this.fnMap.get(fnName);
          if (decl?.returnType) {
            const rt = decl.returnType as any;
            if (rt.kind === NodeKind.GenericType && rt.params && rt.params.length > 0) {
              return this.mapType(rt.params[0]);
            }
            if (rt.inner) {
              return this.mapType(rt.inner);
            }
          }
        }
        return 'vox_str*';
      }
      default: return 'vox_int';
    }
  }

  // ── Field / method resolution ─────────────────────────────

  private getFieldType(className: string, fieldName: string): string | null {
    let cls: ClassDeclNode | undefined = this.classMap.get(className);
    while (cls) {
      const f = cls.members.find(m => m.kind === NodeKind.FieldDecl && (m as FieldDeclNode).name === fieldName) as FieldDeclNode | undefined;
      if (f?.typeAnnot) return this.mapType(f.typeAnnot);
      cls = cls.superClass ? this.classMap.get(cls.superClass) : undefined;
    }
    const info = this.structMap.get(className);
    if (info) { const f = info.fields.find(f => f.name === fieldName); if (f) return this.mapType(f.typeAnnot); }
    return null;
  }

  private getMethodReturnType(className: string, methodName: string): string | null {
    let cls: ClassDeclNode | undefined = this.classMap.get(className);
    while (cls) {
      const m = cls.members.find(m => m.kind === NodeKind.MethodDecl && (m as MethodDeclNode).name === methodName) as MethodDeclNode | undefined;
      if (m?.returnType) return this.mapType(m.returnType);
      cls = cls.superClass ? this.classMap.get(cls.superClass) : undefined;
    }
    return null;
  }

  // ── Predicate helpers ─────────────────────────────────────

  private isLikelyString(node: ExprNode): boolean {
    if (node.kind === NodeKind.StringLiteral) return true;
    if (node.kind === NodeKind.MacroCall && (node as any).name === 'format!') return true;
    if (node.kind === NodeKind.Identifier) return this.varTypeMap.get((node as IdentifierNode).name) === 'vox_str*';
    if (node.kind === NodeKind.MemberExpr || node.kind === NodeKind.CallExpr || node.kind === NodeKind.IndexExpr) return this.inferExprType(node) === 'vox_str*';
    if (node.kind === NodeKind.BinaryExpr && (node as BinaryExprNode).operator === '+') {
      const b = node as BinaryExprNode;
      return this.isLikelyString(b.left) || this.isLikelyString(b.right);
    }
    return false;
  }

  private isLikelyFloat(node: ExprNode): boolean {
    if (node.kind === NodeKind.FloatLiteral) return true;
    if (node.kind === NodeKind.Identifier) return this.varTypeMap.get((node as IdentifierNode).name) === 'vox_float';
    return this.inferExprType(node) === 'vox_float';
  }

  private isLikelyBool(node: ExprNode): boolean {
    if (node.kind === NodeKind.BoolLiteral) return true;
    if (node.kind === NodeKind.Identifier) return this.varTypeMap.get((node as IdentifierNode).name) === 'vox_bool';
    if (node.kind === NodeKind.BinaryExpr) {
      const op = (node as BinaryExprNode).operator;
      if (['==','!=','<','<=','>','>=','&&','||'].includes(op)) return true;
    }
    return this.inferExprType(node) === 'vox_bool';
  }

  private guessClassName(node: ExprNode): string | null {
    if (node.kind === NodeKind.Identifier) {
      const type = this.varTypeMap.get((node as IdentifierNode).name);
      if (type?.startsWith('Vox_') && type.endsWith('*')) return type.slice(4, -1);
      if (type?.startsWith('Vox_') && !type.endsWith('*')) return type.slice(4);
    }
    if (node.kind === NodeKind.NewExpr) return (node as NewExprNode).className;
    return null;
  }

  private toStrExpr(node: ExprNode, expr: string): string {
    const type = this.inferExprType(node);
    if (type === 'vox_option') return `vox_option_to_str(${expr})`;
    if (type === 'vox_result') return `vox_result_to_str(${expr})`;
    if (type === 'vox_set*') return `vox_set_to_str(${expr})`;
    if (type === 'vox_mutex_t*') return `vox_mutex_to_str(${expr})`;
    if (type === 'vox_thread_t*') return `vox_thread_to_str(${expr})`;
    if (type === 'vox_map*') return `vox_map_to_str(${expr})`;
    if (type === 'void*') return `((vox_str*)${expr})`;
    if (this.isLikelyString(node)) return expr;
    if (this.isLikelyFloat(node))  return `vox_float_to_str(${expr})`;
    if (this.isLikelyBool(node))   return `vox_bool_to_str(${expr})`;
    return `vox_int_to_str(${expr})`;
  }

  private genPrint(c: CallExprNode, newline: boolean): string {
    const fn = newline ? 'println' : 'print';
    if (c.args.length === 0) return `vox_${fn}("")`;
    const arg = c.args[0];
    const argExpr = this.generateExpr(arg);
    const inferred = this.inferExprType(arg);
    if (inferred === 'vox_str*' || this.isLikelyString(arg)) return `vox_${fn}_str(${argExpr})`;
    if (inferred === 'vox_float' || this.isLikelyFloat(arg))  return `vox_${fn}_float(${argExpr})`;
    if (inferred === 'vox_bool' || this.isLikelyBool(arg))    return `vox_${fn}_bool(${argExpr})`;
    return `vox_${fn}_int(${argExpr})`;
  }

  private genToStr(arg: ExprNode): string {
    const e = this.generateExpr(arg);
    const type = this.inferExprType(arg);
    if (type === 'vox_option') return `vox_option_to_str(${e})`;
    if (type === 'vox_result') return `vox_result_to_str(${e})`;
    if (type === 'vox_set*') return `vox_set_to_str(${e})`;
    if (type === 'vox_mutex_t*') return `vox_mutex_to_str(${e})`;
    if (type === 'vox_thread_t*') return `vox_thread_to_str(${e})`;
    if (type === 'vox_map*') return `vox_map_to_str(${e})`;
    if (type === 'void*') return `((vox_str*)${e})`;
    if (this.isLikelyString(arg)) return e;
    if (this.isLikelyFloat(arg))  return `vox_float_to_str(${e})`;
    if (this.isLikelyBool(arg))   return `vox_bool_to_str(${e})`;
    return `vox_int_to_str(${e})`;
  }
}
